Fix off-by-one error in degradation.py (#339)
* Fix off-by-one error in degradation.py

Hello!  Thank you for writing such a great package.  I have found an issue with degradation.degradation_year_on_year() that occurs when inputting only two years of data.  It seems as if the package relies on elapsed days to compute the minimum amount of data needed in order to use the method.  It compares the number of days that have passed to 730, but it uses the < operator instead of <= so the method fails for exactly 2 years of data.

This PR fixes that issue.

Thanks!

To reproduce, pass any set of data containing two full years to degradation_year_on_year().  You will see the following traceback:

```
ValueError                                Traceback (most recent call last)
Input In [29], in <cell line: 1>()
----> 1 yearly_rd, yearly_ci, yearly_info = rdtools.degradation_year_on_year(daily.loc[daily.index.year.isin([2017,2018])], confidence_level=68.2)

File ~\Anaconda3\lib\site-packages\rdtools\degradation.py:237, in degradation_year_on_year(energy_normalized, recenter, exceedance_prob, confidence_level)
    234 # Detect less than 2 years of data
    235 if energy_normalized.index[-1] - energy_normalized.index[0] < \
    236         pd.Timedelta('730d'):
--> 237     raise ValueError('must provide at least two years of '
    238                      'normalized energy')
    240 # Auto center
    241 if recenter:

ValueError: must provide at least two years of normalized energy
```

Thanks for your hard work on the package!

* Update degradation.py

* Fix off-by-one error and consider leap years

* tests

* better (?) 2 year check

* shame on me for not linting locally

* changelog entry

* Reconcile change log

* pin flake8 version

* tweak to allow NaN to count for 2 yr requirement

* shuffle check back up to the top

* Revert "pin flake8 version"

This reverts commit 08b4d2562edf6a2ed01371708d8908311b3ebc1d.

Co-authored-by: Kevin Anderson <kevin.anderson@nrel.gov>
Co-authored-by: Michael Deceglie <Michael.Deceglie@nrel.gov>
Co-authored-by: Michael Deceglie <mdeceglie@users.noreply.github.com>